[stable/coredns] Fix missing .fullname to .name label
PR #6093 changed to using .name instead of .fullname but that was missed
in one place, presenting the following error on deployment:
 > Error: release coredns failed: Deployment.apps "coredns-coredns" is
 > invalid: spec.template.metadata.labels: Invalid value:
 > map[string]string{"release":"coredns", "app":"coredns-coredns"}:
 > `selector` does not match template `labels`

Signed-off-by: William Johansson <radar@radhuset.org>