set deployment to apps/v1
Fix the error with deployment not being in version v1beta2:

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

Therefore change the apiVersion to "apps/v1".

Signed-off-by: Rune Nielsen <runeanielsen@live.dk>