Change the Airflow Redis password key name
Dashes are not valid in Golang variable names. Using the
straightforward approach when describing the Airflow Redis secret does
not work as expected.
```
$ kubectl get secret airflow-redis --template={{.data.redis-password}}
error: error parsing template {{.data.redis-password}}, template: output:1: bad character U+002D '-'
```

Instead we need to use the awkward syntax to work around this which
is an unnecessary workaround (notice the single and double quotes)

```
$ kubectl get secret airflow-redis '--template={{.data "redis-password"}}'
```

Signed-off-by: Dani Hodovic <dani.hodovic@gmail.com>