[sparkoperator] fix invalid webhook init job
Prior to this commit, helm validation for webhook-init-job of
incubator/sparkoperator failed in helm3 with the following error:

    Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Job.spec): unknown field "metadata" in io.k8s.api.batch.v1.JobSpec

Issue was introduced by https://github.com/helm/charts/pull/23876 by
accident, as other jobs in this chart (incubator/sparkoperator) were not
affected.

Signed-off-by: Oleksandr Kovalchuk <anxolerd@outlook.com>