Kube 1.16 removed deprecated api (#18856)
* [stable/wordpress] bump major version (#18852)

Helm performs a lookup for the object based on its group (apps), version (v1), and kind (Deployment). Also known as its GroupVersionKind, or GVK. Changing the GVK is considered a compatibility breaker from Kubernetes' point of view, so you cannot "upgrade" those objects to the new GVK in-place. Earlier versions of Helm 3 did not perform the lookup correctly which has since been fixed to match the spec.

In https://github.com/helm/charts/pulls/12642 the `apiVersion` of the deployment resources was updated to `apps/v1` in tune with the api's deprecated, resulting in compatibility breakage.

This major version signifies this change.

Signed-off-by: Sameer Naik <sameersbn@vmware.com>
Signed-off-by: Anish Dhanka <anish@bjshomedelivery.com>

* Kube 1.16 removed deprecated api

Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"
Signed-off-by: Anish Dhanka <anish@bjshomedelivery.com>

* circleci bump chart version issue fixed

Signed-off-by: Anish Dhanka <anish@bjshomedelivery.com>

* mysqlha selector issue fixed

Signed-off-by: Anish Dhanka <anish@bjshomedelivery.com>

Co-authored-by: Sameer Naik <sameersbn@vmware.com>
Co-authored-by: Anish  Dhanka <Anishmourya@users.noreply.github.com>
Signed-off-by: Adrien Loiseau <adrien.loiseau@logic-immo.com>