Fix #2644 traefik chart duplicate value (#2651)
* Fix #2644 traefik chart duplicate value

The logic in place states that if ssl is **NOT** enabled in traefik,
then have the kube service listen on 443 and send to 80. There is
already a port/targetPort setup for 80.

This results in the error described in issue #2644

    Error: release traefik failed: Service "traefik-traefik" is invalid:
spec.ports[1].targetPort: Duplicate value: intstr.IntOrString{Type:0,
IntVal:80, StrVal:""}

My fix is when ssl is not enabled, to add a second traefik listening
port at 84. Which means the service is setup with the following port
mappings:

    80  -> 80
    443 -> 84

The ssl.enabled logic in this chart does not seem to refer to the
service, only traefik itself. My solution is a little copy pasta in that
I add the second http listener, but then I'm not changing/breaking the
ssl.enabled logic.

* Bump chart patch version

(oops)

* Match the endpoint names correctly

* Add the new containerPort 84

* Switch the alternate http port to 8080

After discussing the issue on github I'm moving the alternate http port
from 84 to 8080.

* Use port 8880 to avoid conflicts. Use named ports

In another chart I worked on it was recommended to use named container
ports. I'm following that advice here.

I am also avoiding the 8080 dashboard conflict by switching the http
alternate port (httpn) to 8880.